[07/Nov/2018 05:34:39] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:34:41] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:34:41] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:49:08] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:49:09] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:49:17] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:49:18] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:53:47] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:55:21] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 05:55:24] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 06:04:08] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 06:07:05] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/middleware/common.py", line 62, in process_request
    host = request.get_host()
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 93, in get_host
    if domain and validate_host(domain, settings.ALLOWED_HOSTS):
  File "/home/sanchit/.local/lib/python3.6/site-packages/django/http/request.py", line 570, in validate_host
    pattern = pattern.lower()
AttributeError: type object 'set' has no attribute 'lower'
[07/Nov/2018 10:11:29] DEBUG [django.db.backends:89] (0.036) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[07/Nov/2018 10:11:29] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[07/Nov/2018 10:11:36] WARNING [django.request:170] Not Found: /
[07/Nov/2018 10:22:49] WARNING [django.request:170] Not Found: /
[07/Nov/2018 10:23:01] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[07/Nov/2018 10:23:01] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[07/Nov/2018 10:23:04] WARNING [django.request:170] Not Found: /
[07/Nov/2018 10:23:13] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[07/Nov/2018 10:23:13] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[07/Nov/2018 10:23:18] WARNING [django.request:170] Not Found: /
[07/Nov/2018 10:31:13] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[07/Nov/2018 10:31:13] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[07/Nov/2018 10:31:19] WARNING [django.request:170] Not Found: /
[07/Nov/2018 10:31:57] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[07/Nov/2018 10:31:57] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[07/Nov/2018 10:32:00] WARNING [django.request:170] Not Found: /
[07/Nov/2018 10:32:01] WARNING [django.request:170] Not Found: /
